.env: line 1: HUGGING_FACE_HUB_TOKEN: command not found
/scratch/mjd9571/conda/envs_dirs/juypter/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py:809: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]Loading checkpoint shards:  20%|██        | 1/5 [00:08<00:32,  8.00s/it]Loading checkpoint shards:  40%|████      | 2/5 [00:16<00:25,  8.49s/it]Loading checkpoint shards:  60%|██████    | 3/5 [00:25<00:17,  8.55s/it]Loading checkpoint shards:  80%|████████  | 4/5 [00:33<00:08,  8.52s/it]Loading checkpoint shards: 100%|██████████| 5/5 [00:41<00:00,  8.19s/it]Loading checkpoint shards: 100%|██████████| 5/5 [00:41<00:00,  8.31s/it]
Traceback (most recent call last):
  File "/scratch/mjd9571/VentureAI/mistral_model.py", line 261, in <module>
    itineraries = generate_itinerary(
                  ^^^^^^^^^^^^^^^^^^^
  File "/scratch/mjd9571/VentureAI/mistral_model.py", line 228, in generate_itinerary
    matched_cities = identify_cities_in_input(user_input, city_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/mjd9571/VentureAI/mistral_model.py", line 103, in identify_cities_in_input
    match = re.search(r"'''[^']+''' is in ([^,]+), ([^\.]+)\.", revision_text)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/mjd9571/conda/envs_dirs/juypter/lib/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'dict'
